export enum ErrorCode {
  REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_NOT_FOUND = "REFRESH_TOKEN_NOT_FOUND",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  BLOGGER_NOT_FOUND = "BLOGGER_NOT_FOUND",
  INCORRECT_CURRENT_PASSWORD = "INCORRECT_CURRENT_PASSWORD",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  ACCESS_DENIED = "ACCESS_DENIED"
}
