export enum ErrorCode {
  // NOT FOUND
  REFRESH_TOKEN_NOT_FOUND = "REFRESH_TOKEN_NOT_FOUND",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  RESTAURANT_NOT_FOUND = "RESTAURANT_NOT_FOUND",
  BLOGGER_NOT_FOUND = "BLOGGER_NOT_FOUND",
  MEAL_NOT_FOUND = "MEAL_NOT_FOUND",
  CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND",
  RECOMMENDATION_NOT_FOUND = "RECOMMENDATION_NOT_FOUND",
  NO_MEALS_FOR_RESTAURANT = "NO_MEALS_FOR_RESTAURANT",

  // EXPIRED / INCORRECT / INVALID
  REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED",
  INCORRECT_CURRENT_PASSWORD = "INCORRECT_CURRENT_PASSWORD",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",

  // ALREADY EXISTS
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  CATEGORY_ALREADY_EXISTS = "CATEGORY_ALREADY_EXISTS",
  BLOGGER_ALREADY_EXISTS = "BLOGGER_ALREADY_EXISTS",
  MEAL_ALREADY_EXISTS = "MEAL_ALREADY_EXISTS",
  RESTAURANT_ALREADY_EXISTS = "RESTAURANT_ALREADY_EXISTS",

  // REQUIRED
  AT_LEAST_ONE_LOCATION_REQUIRED = "AT_LEAST_ONE_LOCATION_REQUIRED",

  ACCESS_DENIED = "ACCESS_DENIED"
}
