export enum ErrorCode {
  // NOT FOUND / MISSING / REQUIRED
  REFRESH_TOKEN_NOT_FOUND = "REFRESH_TOKEN_NOT_FOUND",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  RESTAURANT_NOT_FOUND = "RESTAURANT_NOT_FOUND",
  BLOGGER_NOT_FOUND = "BLOGGER_NOT_FOUND",
  MEAL_NOT_FOUND = "MEAL_NOT_FOUND",
  CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND",
  RECOMMENDATION_NOT_FOUND = "RECOMMENDATION_NOT_FOUND",
  NO_MEALS_FOR_RESTAURANT = "NO_MEALS_FOR_RESTAURANT",
  AT_LEAST_ONE_LOCATION_REQUIRED = "AT_LEAST_ONE_LOCATION_REQUIRED",
  NAME_IS_REQUIRED = "NAME_IS_REQUIRED",
  MISSING_GOOGLE_ID_OR_PHONE = "MISSING_GOOGLE_ID_OR_PHONE",
  PASSWORDS_REQUIRED = "PASSWORDS_REQUIRED",

  // EXPIRED / INCORRECT / INVALID
  REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED",
  INCORRECT_CURRENT_PASSWORD = "INCORRECT_CURRENT_PASSWORD",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  INVALID_OTP = "INVALID_OTP",
  USER_NOT_VERIFIED = "USER_NOT_VERIFIED",

  // ALREADY EXISTS
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  CATEGORY_ALREADY_EXISTS = "CATEGORY_ALREADY_EXISTS",
  BLOGGER_ALREADY_EXISTS = "BLOGGER_ALREADY_EXISTS",
  MEAL_ALREADY_EXISTS = "MEAL_ALREADY_EXISTS",
  RESTAURANT_ALREADY_EXISTS = "RESTAURANT_ALREADY_EXISTS",
  RECOMMENDATION_ALREADY_EXISTS = "RECOMMENDATION_ALREADY_EXISTS",
  USER_ALREADY_VERIFIED = "USER_ALREADY_VERIFIED",

  ACCESS_DENIED = "ACCESS_DENIED",

  ONE_OR_MANY_MEAL_BELONG_TO_ANOTHER_RESTAURANT = "ONE_OR_MANY_MEAL_BELONG_TO_ANOTHER_RESTAURANT"
}
